# Generated by Django 4.1 on 2023-03-20 16:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('D', 'Disapproved'), ('P', 'Pending')], default='P', max_length=1)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phonenumber', models.CharField(max_length=18)),
                ('job', models.CharField(max_length=5, verbose_name='Job code')),
                ('personality', models.CharField(choices=[('I am outgoing', 'I am outgoing'), ('I am antisocial', 'I am antisocial'), ('I am serious', 'I am serious')], max_length=50, null=True)),
                ('salary', models.CharField(max_length=50, verbose_name='Salary expectation')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('experience', models.BooleanField(null=True)),
                ('smoker', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1)),
                ('file', models.FileField(upload_to='files')),
                ('image', models.ImageField(default='images/picture.jpg', upload_to='images')),
                ('note', models.TextField(blank=True)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Java', 'Java'), ('Haskell', 'Haskell')], max_length=50)),
                ('frameworks', multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Vue', 'Vue'), ('Flask', 'Flask'), ('Others', 'Others')], max_length=50)),
                ('databases', multiselectfield.db.fields.MultiSelectField(choices=[('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('Redis', 'Redis'), ('Cassandra', 'Cassandra'), ('Sqlite3', 'Sqlite3'), ('Oracle', 'Oracle')], max_length=50)),
                ('libraries', multiselectfield.db.fields.MultiSelectField(choices=[('jQuery', 'jQuery'), ('Bootstrap', 'Bootstrap'), ('Ajax', 'Ajax'), ('HTMX', 'HTMX'), ('AlpineJS', 'AlpineJS'), ('Tensorflow', 'Tensorflow')], max_length=50)),
                ('mobile', multiselectfield.db.fields.MultiSelectField(choices=[('React native', 'React native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Dart', 'Dart'), ('Xamarin', 'Xamarin'), ('Ionic', 'Ionic')], max_length=50)),
                ('others', multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('VScode', 'VScode'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Linux', 'Linux')], max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('started_course', models.DateField()),
                ('finished_course', models.DateField(blank=True, null=True)),
                ('course_description', models.TextField()),
                ('course_status', models.CharField(choices=[('', 'Select course status'), ('I am studying', 'I am studying'), ('I want to study course', 'I want to study course'), ('I have completed the course', 'I have completed the course')], max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('started_job', models.DateField(blank=True, null=True)),
                ('finished_job', models.DateField(blank=True, null=True)),
                ('about_job', models.TextField()),
                ('employed', models.BooleanField(verbose_name='I am employed')),
                ('remote', models.BooleanField(verbose_name='I agree to work remotely')),
                ('travel', models.BooleanField(verbose_name='I am available for travel')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=50)),
                ('chat', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Read'), ('P', 'Pending')], default='P', max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=25)),
                ('body', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(default=False, verbose_name='Took responsibility')),
                ('message', models.TextField()),
                ('person', models.CharField(choices=[('E', 'Employee'), ('C', 'Candidate')], max_length=10)),
                ('subject', models.CharField(choices=[('I lost my account', 'I lost my account'), ('My password does not work', 'My password does not work'), ('Update resume', 'Update resume'), ('Others', 'Others')], max_length=50)),
                ('status', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='P', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.PositiveIntegerField(default=0)),
                ('backend', models.PositiveIntegerField(default=0)),
                ('devops', models.PositiveIntegerField(default=0)),
                ('design', models.PositiveIntegerField(default=0)),
                ('timer', models.CharField(max_length=100)),
            ],
        ),
    ]
