# Generated by Django 4.0.4 on 2022-05-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(default=False, verbose_name='Took responsibility')),
                ('message', models.TextField()),
                ('person', models.CharField(choices=[('E', 'Employee'), ('C', 'Candidate')], max_length=10)),
                ('subject', models.CharField(choices=[('I lost my account', 'I lost my account'), ('My password does not work', 'My password does not work'), ('Update resume', 'Update resume'), ('Others', 'Others')], max_length=50)),
                ('status', models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='P', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
