# Generated by Django 4.0.4 on 2022-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.CharField(max_length=100)),
                ('backend', models.CharField(max_length=100)),
                ('devops', models.CharField(max_length=100)),
                ('design', models.CharField(max_length=100)),
            ],
        ),
    ]
