# Generated by Django 4.0.4 on 2022-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='backend',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='design',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='devops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='frontend',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
