# Generated by Django 4.0.4 on 2022-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_alter_vacancy_backend_alter_vacancy_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='timer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
