# Generated by Django 4.1 on 2022-09-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0008_alter_message_options_alter_message_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='resume')),
                ('company_note', models.TextField(blank=True)),
            ],
        ),
    ]
