# Generated by Django 4.1 on 2022-09-14 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0010_candidate_age_alter_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=18),
            preserve_default=False,
        ),
    ]
