# Generated by Django 4.1 on 2022-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0012_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('R', 'Approved'), ('D', 'Disapproved'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
