# Generated by Django 4.1 on 2022-09-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0013_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Disapproved'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
