# Generated by Django 4.1 on 2022-09-15 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0019_remove_candidate_age_candidate_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about_job',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_status',
            field=models.CharField(choices=[('', 'Select course status'), ('I am studying', 'I am studying'), ('I want to study course', 'I want to study course'), ('I have completed the course', 'I have completed the course')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='employed',
            field=models.BooleanField(default=1, verbose_name='I am employed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_course',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_job',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='remote',
            field=models.BooleanField(default=1, verbose_name='I agree to work remotely'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_course',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_job',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='travel',
            field=models.BooleanField(default=1, verbose_name='I am available for travel'),
            preserve_default=False,
        ),
    ]
