# Generated by Django 4.1 on 2022-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0020_candidate_about_job_candidate_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.CharField(max_length=5, verbose_name='Job code'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.CharField(max_length=50, verbose_name='Salary expectation'),
        ),
    ]
