# Generated by Django 4.1 on 2022-09-30 08:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0021_alter_candidate_gender_alter_candidate_job_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('Redis', 'Redis'), ('Cassandra', 'Cassandra'), ('Sqlite3', 'Sqlite3'), ('Oracle', 'Oracle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Vue', 'Vue'), ('Flask', 'Flask'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Java', 'Java'), ('Haskell', 'Haskell')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jQuery', 'jQuery'), ('Bootstrap', 'Bootstrap'), ('Ajax', 'Ajax'), ('HTMX', 'HTMX'), ('AlpineJS', 'AlpineJS'), ('Tensorflow', 'Tensorflow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React native', 'React native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Dart', 'Dart'), ('Xamarin', 'Xamarin'), ('Ionic', 'Ionic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('VScode', 'VScode'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Linux', 'Linux')], max_length=50),
        ),
    ]
