# Generated by Django 4.1 on 2022-12-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0022_alter_candidate_options_alter_candidate_databases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='finished_job',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='started_job',
            field=models.DateField(blank=True, null=True),
        ),
    ]
